### ISSUE TITLE
Invalid Threshhold Values

### ISSUE THREAD

**Issue by Jiaro** [LamaTe/mlr3shiny#35]
The UI prints out an error message on xgboost and ranger when analysing german_credit_data -> Invalid Values

**Comment by LamaTe** [comment]
Affected systems: Windows OS

Details: 
Shiny seems to interpret empty values differently on Linux OS vs Windows OS, where Linux OS is handled as NAs and Windows OS a conversion to 0 happens. Needs closer investigation. 
Need a good fix to either feed defaults through ranger / xgboost or directly mlr. Otherwise, code defaults if an empty value is handed by the user. 

Affected files:
server_learner.R

**Comment by LamaTe** [comment]
See PR #51
